name: Auto Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: SSH to VPS and deploy
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd /root/travelogue/SEP490.Travelogue.API

            mkdir -p Travelogue.API/Config

            echo "${{ secrets.APPSETTINGS_JSON }}" | base64 -d > Travelogue.API/appsettings.json

            echo "${{ secrets.FIREBASE_KEY_JSON }}" | base64 -d > Travelogue.API/Config/serviceAccountKey.json

            git pull origin main

            docker compose down || docker-compose down
            docker compose up --build -d || docker-compose up --build -d
          EOF
